name: CI

on:
  push:
    branches: [ main ]
    tags:
      - "*"
  pull_request:
    branches:
      - "*"
  schedule:
    # Daily at 06:13
    - cron: '13 6 * * *'

defaults:
  run:
    shell: bash

jobs:
  ci:
    name: ${{ matrix.os.name }} - ${{ matrix.python.name }}
    runs-on: ${{ matrix.os.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - name: Linux
            runs-on: ubuntu-latest
          - name: Windows
            runs-on: windows-latest
          - name: macOS
            runs-on: macos-latest
        python:
          - name: CPython 2.7
            action: 2.7
          - name: CPython 3.5
            action: 3.5
          - name: CPython 3.6
            action: 3.6
          - name: CPython 3.7
            action: 3.7
          - name: CPython 3.8
            action: 3.8
          - name: CPython 3.9
            action: 3.9
          - name: PyPy 2.7
            action: pypy-2.7
          - name: PyPy 3.6
            action: pypy-3.6
          - name: PyPy 3.7
            action: pypy-3.7

    steps:
    - uses: actions/checkout@v2

    - name: Set up ${{ matrix.python.name }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python.action }}

    - name: Cover some
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install coverage
        python -m coverage run test.py

    - name: Run the action
      uses: ./
      with:
        id: ${{ matrix.os.name }} - ${{ matrix.python.name }}

  check:
    name: Check
    runs-on: ubuntu-latest
    needs:
      - ci
    steps:
      - name: Download coverage
        uses: actions/download-artifact@v2
        with:
          name: coverage
          path: coverage_reports

      - name: Test
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install coverage

      - name: Combine coverage
        run: |
          python -m coverage combine coverage_reports/*

      - name: Confirm coverage incomplete
        run: |
          if python -m coverage report --fail-under 100; then false; fi

      - name: Complete coverage
        run: |
          python -m coverage run --append test.py --cover-it

      - name: Confirm coverage complete
        run: |
          python -m coverage report --fail-under 100

  all:
    name: All
    runs-on: ubuntu-latest
    needs:
      - ci
      - check
    steps:
      - name: This
        shell: python
        run: |
          import this
